In [1]:
import tensorflow as tf

##  Shape of Conv2D

In [2]:
from tensorflow.keras.layers import Conv2D

In [10]:
N, n_H, n_W, n_C = 1, 28, 28, 5
n_filter = 10
k_size = 3

images = tf.random.uniform(minval = 0, maxval = 1, shape = ((N, n_H, n_W, n_C)))

conv = Conv2D(filters = n_filter, kernel_size = k_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape)
print(B.shape)
print(y.shape)

(1, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(1, 26, 26, 10)


## Correlation Calculation

In [16]:
import numpy as np
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1
k_size = 3

images = tf.random.uniform(minval = 0, maxval = 1, shape = ((N, n_H, n_W, n_C)))

conv = Conv2D(filters = n_filter, kernel_size = k_size)

y = conv(images)
print('y(Tensorflow): \n', y.numpy().squeeze()) # 1 제거

W, B = conv.get_weights()

images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape =(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
        window = images[i : i + k_size, j : j + k_size]
        y_man[i, j] = np.sum(window * W) + B
        
print('y(Manual): \n', y_man)

y(Tensorflow): 
 [[-0.20938356 -0.720262   -0.5615284 ]
 [-0.98993313 -0.37307164 -0.8702488 ]
 [-0.85484046 -0.6811026  -0.25249296]]
y(Manual): 
 [[-0.20938359 -0.72026193 -0.56152833]
 [-0.98993337 -0.37307161 -0.87024879]
 [-0.85484052 -0.68110263 -0.2524929 ]]
