### Activation Functions

#### Activation Layers

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Activation
from tensorflow import math #exp, maximum

In [2]:
x = tf.random.uniform(shape =(1, 5))  #Input setting

#activation functions
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

#forward propagation(Tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

#forward propagation(Manual)
y_sigmoid_man = 1 / (1 + math.exp(-x))
y_tanh_man = (math.exp(x) - math.exp(-x)) / ((math.exp(x)) + math.exp(-x))
y_relu_man = math.maximum(x, 0)

print("x : {}\n{}".format(x.shape, x.numpy()))
print("Sigmoid(Tensorflow): {}\n{}".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("Sigmoid(Manual): {}\n{}".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))
print("Tanh(Tensorflow): {}\n{}".format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("Tanh(Manual): {}\n{}".format(y_tanh_man.shape, y_tanh_man.numpy()))
print("Relu(Tensorflow): {}\n{}".format(y_relu_tf.shape, y_relu_tf.numpy()))
print("Relu(Manual): {}\n{}".format(y_relu_man.shape, y_relu_man.numpy()))

x : (1, 5)
[[0.55708027 0.46852636 0.72121286 0.00457382 0.19084108]]
Sigmoid(Tensorflow): (1, 5)
[[0.6357767  0.61503494 0.6728741  0.50114346 0.547566  ]]
Sigmoid(Manual): (1, 5)
[[0.6357767  0.61503494 0.6728741  0.50114346 0.547566  ]]
Tanh(Tensorflow): (1, 5)
[[0.50580794 0.43700787 0.61766005 0.00457379 0.18855752]]
Tanh(Manual): (1, 5)
[[0.5058079  0.4370079  0.61766005 0.0045738  0.18855749]]
Relu(Tensorflow): (1, 5)
[[0.55708027 0.46852636 0.72121286 0.00457382 0.19084108]]
Relu(Manual): (1, 5)
[[0.55708027 0.46852636 0.72121286 0.00457382 0.19084108]]


#### Activation in Dense Layer

In [3]:
import tensorflow as tf
from tensorflow import math
from tensorflow.keras.layers import Dense, Activation

x = tf.random.uniform(shape = (1, 5)) # input setting

dense_sigmoid = Dense(units = 1, activation = 'sigmoid')
dense_tanh = Dense(units = 1, activation = 'tanh')
dense_relu = Dense(units = 1, activation = 'relu')

y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print("AN with sigmoid: {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("AN with tanh: {}\n{}".format(y_tanh.shape, y_tanh.numpy()))
print("AN with relu: {}\n{}".format(y_relu.shape, y_relu.numpy()))

AN with sigmoid: (1, 1)
[[0.7037987]]
AN with tanh: (1, 1)
[[-0.9129645]]
AN with relu: (1, 1)
[[0.]]


In [5]:
print("\n======\n")

W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1 / (1 + math.exp(-z))

print("Activation Value(Tensorflow) : {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("Activation Value(Manual) : {}\n{}".format(a.shape, a.numpy()))



Activation Value(Tensorflow) : (1, 1)
[[0.7037987]]
Activation Value(Manual) : (1, 1)
[[0.7037987]]


### Minibatches

#### Shapes of Dense Layers

In [10]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_features = 32000, 10 #set input param

x = tf.random.normal(shape = (N, n_features)) # generate minibatch

dense = Dense(units = 1, activation = 'relu')
y = dense(x)

W, B = dense.get_weights()

print("Shape of x : {}".format(x.shape))
print("Shape of W : {}".format(W.shape))
print("Shape of B : {}".format(B.shape))

Shape of x : (32000, 10)
Shape of W : (10, 1)
Shape of B : (1,)


#### Output Calculation

In [12]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_features = 8, 10 #set input param
x = tf.random.normal(shape = (N, n_features)) # generate minibatch

dense = Dense(units = 1, activation = 'relu')
y_tf = dense(x) #forward propagation(Tensorflow)

W, B = dense.get_weights() # get weights/bias

y_man = tf.linalg.matmul(x, W) + B  # forward propagation(Manual)

#print results

print("Outputs(Tensorflow) : \n", y_tf.numpy())
print("Outputs(Manual) : \n", y_man.numpy())
print(tf.math.equal(y_tf, y_man))

Outputs(Tensorflow) : 
 [[1.012841  ]
 [0.88561225]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [1.2336811 ]]
Outputs(Manual) : 
 [[ 1.012841  ]
 [ 0.88561225]
 [-0.54740274]
 [-1.5447688 ]
 [-1.3922534 ]
 [-0.3420809 ]
 [-0.5438303 ]
 [ 1.2336811 ]]
tf.Tensor(
[[ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]], shape=(8, 1), dtype=bool)
