In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

In [10]:
x = tf.constant([[10.]])
print(x)

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)


In [13]:
dense = Dense(units = 1, activation = 'linear')

y_tf = dense(x) 

W, B = dense.get_weights()
print('Weight : ', W, ', Bias : ', B)

y_man = tf.linalg.matmul(x, W) + B

Weight :  [[1.640169]] , Bias :  [0.]


In [14]:
#print results
print('x: {}\n{}\n'.format(x.shape, x.numpy()))
print('w: {}\n{}\n'.format(W.shape, W))
print('b: {}\n{}\n'.format(B.shape, B))

x: (1, 1)
[[10.]]

w: (1, 1)
[[1.640169]]

b: (1,)
[0.]



In [15]:
print('y(Tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf))
print('y(Manual): {}\n{}\n'.format(y_man.shape, y_man))

y(Tensorflow): (1, 1)
[[16.40169]]

y(Manual): (1, 1)
[[16.40169]]



### Params Initialization

In [19]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

x = tf.constant([[10.]])

w, b = tf.constant(10.), tf.constant(20.)

In [24]:
w_init, b_init = Constant(w.numpy()), Constant(b.numpy())

dense = Dense(units = 1,
             activation = 'linear',
             kernel_initializer = w_init,
             bias_initializer = b_init)

y_tf = dense(x)
print(y_tf)
W, B = dense.get_weights()

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)


In [25]:
print('w: {}\n{}\n'.format(W.shape, W))
print('b: {}\n{}\n'.format(B.shape, B))

w: (1, 1)
[[10.]]

b: (1,)
[20.]



### Affine functions with n Features

In [28]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape = (1, 10), minval = 0, maxval = 10)
print(x.shape, '\n', x)

(1, 10) 
 tf.Tensor(
[[0.524174   0.6546807  2.3699093  5.1990995  0.19704461 7.6795936
  5.6720104  7.054323   0.2799213  8.895503  ]], shape=(1, 10), dtype=float32)


In [30]:
dense = Dense(units = 1)

y_tf = dense(x)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B

print('===== Input/Weight/Bias ====')
print('x: {}\n{}\n'.format(x.shape, x.numpy()))
print('w: {}\n{}\n'.format(W.shape, W))
print('b: {}\n{}\n'.format(B.shape, B))

print('==== Outputs ====')
print('y(Tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf))
print('y(Manual): {}\n{}\n'.format(y_man.shape, y_man))

===== Input/Weight/Bias ====
x: (1, 10)
[[0.524174   0.6546807  2.3699093  5.1990995  0.19704461 7.6795936
  5.6720104  7.054323   0.2799213  8.895503  ]]

w: (10, 1)
[[ 0.2295196 ]
 [-0.22070467]
 [-0.47969908]
 [-0.10780239]
 [-0.3188645 ]
 [ 0.35133535]
 [-0.3930435 ]
 [-0.4524714 ]
 [-0.61415756]
 [ 0.5910025 ]]

b: (1,)
[0.]

==== Outputs ====
y(Tensorflow): (1, 1)
[[0.5779028]]

y(Manual): (1, 1)
[[0.5779028]]

